# This workflow checks the code for errors and then runs tests.
name: CI

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-20.04
    name: 'Check code'

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - name: Check types
        run: nix-shell --run 'mypy --ignore-missing-imports src'
